Full_project/ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

Full_project/chat/urls.py
from os import name
from django.contrib.auth.views import LogoutView as logout
from django.urls import path, re_path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chats/', views.chats, name='chats'),
    path('chat/<int:chat_id>/', views.message_view, name='chat'),
    path('ajax/nightmode/', views.nightmode, name='nightmode'),
    path('ajax/createchat/', views.createchat, name="createchat"),
    path('ajax/search_contacts/', views.search_contacts, name="search_contacts"),
    path('ajax/send_message/', views.send_message, name='send_message'),
    path('ajax/invite_user/', views.invite_user, name="invite_user"),
    path('ajax/send_comment/', views.add_comment, name="add_comment"),
    path('ajax/random_chat/', views.randomchat, name="randomchat"),
    path('logout/', logout.as_view(next_page='index'), {'next_page': 'index'}, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/', views.profile, name='profile'),
    path('contacts/', views.contacts, name="contacts"),
    path('comments/', views.comments, name="comments"),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('join/<str:link>/', views.join, name="join"),
]

Full_project/chat/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.conf import settings
import string, random


class AccountManager(BaseUserManager):
    def create_user(self, email=None, username=None, password=None):
        # if not email:
        #     raise ValueError("Users must have an email adress")
        if not username:
            raise ValueError("Users must have a username")
        # if not password:
        #     raise ValueError("Users must have a password")

        user = self.model(
            email = self.normalize_email(email),
            username=username,
        )

        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, username, password):
        if not email:
            raise ValueError("Users must have an email adress")
        if not username:
            raise ValueError("Users must have a username")
        if not password:
            raise ValueError("Users must have a password")

        user = self.model(
            email = self.normalize_email(email),
            username=username,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class Chat(models.Model):
    name = models.CharField(max_length=40, unique=False, default="chat")
    keyword = models.CharField(max_length=200, unique=False, default="Flowers")
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="members")
    messages_count = models.IntegerField(default=0)
    created = models.DateField(auto_now_add=True)
    last_active = models.DateField(auto_now_add=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="creator")
    private = models.BooleanField(default=True, verbose_name="private")

    def __str__(self):
        return f"Chat({self.name}<{self.private}>)"
    
    def add_message(self):
        self.messages_count+=1
        return self.messages_count

class User(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=False)
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=30)
    nightmode = models.BooleanField(verbose_name="night_mode", default=True)
    messages_count = models.IntegerField(default=0)
    is_guest = models.BooleanField(verbose_name="guest", default=False)
    avatar = models.ImageField(verbose_name="avatar")
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email", "password"]

    objects = AccountManager()

    def __str__(self):
        return self.username
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True
    
    def add_message(self):
        self.messages_count+=1
        return self.messages_count

class Message(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    chat = models.ForeignKey(to=Chat, on_delete=models.CASCADE)
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

class Invite(models.Model):
    url = models.CharField(max_length=20, unique=True)
    chat = models.ForeignKey(to=Chat, on_delete=models.CASCADE)
    creator = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    used = models.IntegerField(default=0)

    def use(self):
        self.used+=1
        return self.used
    
    def generate_url(self):
        url = ""
        for _ in range(10):
            url+=random.choice(string.ascii_letters)
        return url

class Comment(models.Model):
    message = models.CharField(max_length=1000)
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Guest_Count(models.Model):
    count = models.IntegerField(default=0)

    def __str__(self):
        return f"Guest_Count({self.count})"
    
    def add(self):
        self.count += 1
        return self.count

    @property
    def c(self):
        return self.count

Full_project/chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import TextInput
from django.contrib.auth import get_user_model
User = get_user_model()


class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields=['username','email','password1','password2']
        widgets = {
            'username': TextInput(attrs={'class':'form-control'}),
        }

Full_project/chat/views.py
import re, random, datetime
from django import forms
from . import forms as _forms
from django.contrib.auth import authenticate, login
from django.http.response import Http404, HttpResponseBadRequest, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from chat.models import Message
from chat.forms import SignUpForm
from chat.serializers import MessageSerializer, UserSerializer
from django.core import serializers
from . import models
from django.contrib.auth import get_user_model

User = get_user_model()
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "chat.html" 

def index(request):
    if request.user.is_authenticated:
        return redirect('chats')
    if request.method == 'GET':
        return render(request, 'chat/index.html', {})
    if request.method == "POST":
        print(request.POST)
        if "guest" in request.POST:
            if len(models.Guest_Count.objects.all()):
                counter =  models.Guest_Count.objects.all()[0]
            else:
                counter = models.Guest_Count()
            count = counter.add()
            counter.save()
            guest = User(username=f"Guest{count}", password="password", nightmode=True, email="guest@email", is_guest=True)
            guest.save()
            login(request, guest, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('chats')
        if not len(request.POST["username"]) or not len(request.POST["password"]):
            return redirect('index')
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            return HttpResponse('{"error": "User does not exist"}')
        return redirect('chats')



@csrf_exempt
def message_list(request, sender=None, receiver=None):
    """
    List all required messages, or create a new message.
    """
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


def register_view(request):
    """
    Render registration template
    """
    if request.method == 'POST':
        # print("working1")
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                    return redirect('chats')
    else:
        # print("working2")
        form = SignUpForm()
    template = 'chat/register.html'
    context = {'form':form}
    return render(request, template, context)

@csrf_exempt
def chats(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        user = request.user
        public_chats = models.Chat.objects.filter(private=False)
        private_chats = []
        for chat in models.Chat.objects.filter(private=True):
            if user in chat.members.all(): private_chats.append(chat)
        return render(request, 'chat/chat.html',
                      {'user': user, "private_chats": private_chats, "public_chats":public_chats})

@csrf_exempt
def send_message(request):
    if request.method == "POST":
        chat = models.Chat.objects.filter(id=request.POST['chat_id'])[0]
        chat.add_message()
        chat.save()
        request.user.add_message()
        request.user.save()
        message = models.Message(author=request.user, message=request.POST['message'], is_read=False, chat=chat)
        message.save()
        return JsonResponse({"author_name":request.user.username, "message":request.POST['message']})

@csrf_exempt
def add_comment(request):
    if request.user.is_guest:
        return JsonResponse({"guest":request.user.username})
    comment = models.Comment(message=request.POST["comment"], author=request.user)
    comment.save()
    return JsonResponse({"message":request.POST['comment'], "author":request.user.username})

def nightmode(request):
    if request.method == "GET":
        mode = request.GET["nightmode"]
        # print(mode)
        mode = not (mode == "True") and not (mode == "true")
        user = User.objects.filter(username=request.user.username)[0]
        user.nightmode = mode
        user.save()
        # print(mode)
        data = {"nightmode": mode}
        return JsonResponse(data)

def randomchat(request):
    public_chats = models.Chat.objects.filter(private=False)
    private_chats = []
    for chat in models.Chat.objects.filter(private=True):
        if request.user in chat.members.all(): private_chats.append(chat)
    chats = list(public_chats)+private_chats
    if not len(chats):
        return redirect('index')
    chat = random.choice(chats)
    return JsonResponse({"url":f"{request.scheme}://{request.get_host()}/chat/{chat.id}/"})

@csrf_exempt
def createchat(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "POST":
        data = request.POST
        # print(data)
        chat = models.Chat(name=data["chatname"], creator=request.user, private=(data["state"]=="private"))
        chat.save()
        chat.members.add(request.user)
        # print(chat)
        return JsonResponse({"url":f"{request.scheme}://{request.get_host()}/chat/{chat.id}/"})

def message_view(request, chat_id):
    if not request.user.is_authenticated:
        return redirect('index')
    chat = models.Chat.objects.filter(id=chat_id)[0]
    members = chat.members.all() if chat.private else User.objects.filter(is_guest=False)
    #if request.user not in members:
        #return redirect('join')
    messages = models.Message.objects.filter(chat=chat)
    return render(request, "chat/messages.html",
                      {'messages': messages, "chat":chat, "members":members})

def profile(request):
    if not request.user.is_authenticated:
        return redirect('index')
    chats = models.Chat.objects
    popular = chats.order_by("-messages_count")
    unpopular = popular.reverse()
    pub_chats_count = len(models.Chat.objects.filter(private=False))
    priv_chats_count = len(models.Chat.objects.filter(private=True))
    chats_count_user = len(models.Chat.objects.filter(creator=request.user))
    messages_count = len(models.Message.objects.filter(author=request.user))
    allmessages = len(models.Message.objects.filter())
    status_dict = {100:'Begginer',500:'Standard',2500:'Alcoholic', 10000:'Crazy man', 15000:'Flooder'}
    status_num = {'Begginer':1,'Standard':2,'Alcoholic':3,'Crazy man':4,'Flooder':5}
    users = User.objects.filter(is_guest=False).order_by("-messages_count")[:5]
    a_users = len(User.objects.filter(is_guest=True))
    now = datetime.datetime.now()
    chats_today = len(models.Chat.objects.filter(created__year=now.year, created__month=now.month, created__day=now.day, creator=request.user))
    for item in status_dict:
        if messages_count > item and item != 15000:
            continue
        status = status_dict[item] if messages_count <= item else "Flooder"
        break
    return render(request, 'chat/profile.html', {"popular_chats":popular[:5],"user_status":[status, status_num[status]],
     "unpopular_chats":unpopular[:5], "private_count":priv_chats_count, "public_count":pub_chats_count, "messages":messages_count, "users":users, "a_users":a_users, "chats_today":chats_today, "chats_count_user":chats_count_user, "allmessages": allmessages})

def group(request):
    return render(request, "chat/group.html")

def contacts(request):
    if not request.user.is_authenticated:
        return redirect('index')
    return render(request, "chat/contacts.html",
            {   "user":request.user,
                "users":User.objects.exclude(username=request.user.username).exclude(is_guest=True),
                })
    
@csrf_exempt
def search_contacts(request):
    if request.method == "GET":
        print(request.GET)
        users = User.objects.exclude(is_guest=True).exclude(username=request.user.username)
        term = request.GET['term'].lower()
        resp = []
        for item in users:
            if term in item.username.lower():
                print(term, item.username)
                resp.append({"name":item.username, "email":item.email})
        print(resp)
        return JsonResponse({"users":resp}) # {"users":[{"name":name1,"email":email1}]}

def invite_user(request):
    if request.method == "GET":
        invite = models.Invite(chat=models.Chat.objects.filter(id=request.GET["chat_id"])[0], creator=request.user)
        url = invite.generate_url()
        while len(models.Invite.objects.filter(url=url)):
            url = invite.generate_url()
        invite.url = url
        invite.save()

Full_project/templates/chat/chat.html
{% extends 'chat/sidepanel.html' %}

{% load static%}
{% block stylesChat%}
    <link type="text/css" rel="stylesheet" href="{% static 'css/copyit.css' %}">
{% endblock%}

{% block body %}

<div class="section">
    <div class="row">
        
        {% block configuration%}
        <div class="col-12 col-xs-12 col-sm-12 col-md-3 px-0">
            <div class="card" style='height:94vh;'>
        {% endblock %}                    
                
                {% block usersORchats%}

                    <div class="nightmode_changed_color collection" style='height:93vh; overflow-y: auto;'>
                        <!-- Private Chats -->
                        <div class="bodyTitle">
                            <button id='button_generate' class="buttonload">
                            <i class="fa fa-spinner fa-spin"></i> Random Chat
                            </button>
                            <h1 class='titleDesc'>Private chats</h1>
                        </div>

                        {% for chat in private_chats %}
                        <a href="{% url 'chat' chat.id %}" id="user{{ user.id }}" class="collection-item row">
                            {% load static %}
                            <img src="{% static 'img/beer.png' %}" alt="Beeeeeer" class="col s4">
                            <div class="col s8">
                                <span class="title" style="font-weight: bolder">{{ chat.name }}</span>
                            </div>
                        </a>
                        {% endfor %}


                        <!-- Public Chats -->
                        <div>
                            <h1>Public chats</h1>
                        </div>
                        {% for chat in public_chats %}
                        <a href="{% url 'chat' chat.id %}" id="user{{ user.id }}" class="collection-item row">
                            {% load static %}
                            <img src="{% static 'img/beer.png' %}" alt="Beeeeeer" class="col s4">
                            <div class="col s8">
                                <span class="title" style="font-weight: bolder">{{ chat.name }}</span>
                            </div>
                        </a>
                        {% endfor %}

                    </div>
                {% endblock %}
            </div>
        </div>
        
        <div class="col-12 col-xs-12 col-sm-12 col-md-9 px-0 nightmode_changed_color section">
            <div class="card" style='border: 0px solid rgba(0,0,0,0);'>
                <div id="board" class="nightmode_changed_color section">

                    {% block mess %}
                    {% endblock %}

                    {% block input%}
                    {% endblock %}

                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}
{% block javascript %}{% endblock %}

Full_project/templates/chat/comments.html
{% extends 'chat/sidepanel.html' %}

{% load static %}
{% block stylesChat %}<link type="text/css" rel="stylesheet" href="{% static 'css/contacts.css' %}">{% endblock %}
{% block style %}<link type="text/css" rel="stylesheet" href="{% static 'css/comments.css' %}">{% endblock %}

{% block body %}

    <div class="nightmode_changed_color" id='contacts_scroll'>

        <div class="nightmode_changed_color card card-default" id="card_contacts" style='height: 100vh;'>
            <div id="contacts" class="panel-collapse collapse show" aria-expanded="true">
                <div class='comments_block'>
                {% for comment in comments %}
                    <div class="container">
                        <img src="https://st2.depositphotos.com/1010550/7946/i/600/depositphotos_79461036-stock-photo-standing-boys-silhouette.jpg"
                            alt="Avatar" style="width:90px">
                        <p><span>{{ comment.author.username }}</span></p>
                        <p>{{comment.message }}</p>
                    </div>
                {% endfor %}
                </div>

                 <div class="card_add">
                    <div class="input_message__position">
                        <div class="input-field">
                            <input required='' autofocus='' id="id_message" name="message" type="text"
                                placeholder="Type your message..">
                        </div>
                    </div>

                    <div class="icon_message__position">
                        <button id="send-comment" class="btn btn-floating blue lighten-2 waves-effect waves-light"
                            style="border-radius: 50%;padding: 0px 3px;">
                            <i class="material-icons">send</i></button>
                    </div>
                </div>
            </div>
            
        </div>
       
    </div>
    <script type="text/javascript" src="{% static 'js/add_comment.js' %}"></script>

    {% block javascript %}{% endblock %}
    {% block content %}{% endblock %}
    
{% endblock %}

Full_project/templates/chat/contacts.html
{% extends 'chat/sidepanel.html' %}

{% load static %}
{% block stylesChat %}<link type="text/css" rel="stylesheet" href="{% static 'css/contacts.css' %}">{% endblock %}

{% block body %}

    <div class="nightmode_changed_color container-fluid" id='contacts_scroll'>
        <!-- contacts card -->
        <form class="form-inline" action="{% url 'contacts' %}" style='justify-content: space-between;'>
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" id="search_input">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id ="search_button">Search</button>
        </form>

        <div class="nightmode_changed_color card card-default" id="card_contacts" style='height: 100vh;'>
            <div id="contacts" class="panel-collapse collapse show" aria-expanded="true">
                
                <ul class="list-group pull-down" id="contact-list">   
                    {% for user in users %}
                    <li class="noHover">
                        <div class="row w-90">
                            <div class="col-12 col-sm-6 col-md-3 px-0">
                                {% load static %}
                                <img src="{% static 'img/logo.png' %}" alt="Beeeeeer" alt="img" style="width: 100px; height: 100px; padding: 10px; "class="rounded-circle mx-auto d-block img-fluid">
                            </div>
                            <div class="col-12 col-sm-6 col-md-9 text-center text-sm-left">
                                <span class="fa fa-mobile fa-2x text-success float-right pulse" title="online now"></span>
                                <label class="name lead">{{ user.username }}</label>
                                <br> 
                                <span class="fa fa-map-marker fa-fw text-muted" data-toggle="tooltip style="width: auto;"></span>
                                <span class="text-muted">Ukraine</span>
                                <br>
                                <span class="fa fa-envelope fa-fw text-muted" data-toggle="tooltip"></span>
                                <span class="text-muted small text-truncate">{{ user.email }}</span>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>
    
    <script src="{% static 'js/search_contacts.js' %}"></script>
{% endblock %}

Full_project/templates/chat/messages.html
{% extends 'chat/chat.html' %}
{% load static %}
{% block title %} <title>Pivchat - {{ chat.name}}</title> {% endblock %}
{% block configuration%}
    <div class="col-12 d-none d-md-block col-xs-12 col-sm-12 col-md-3 px-0">
    <div class="nightmode_changed_color card" style='height:94vh; overflow-x:hidden;padding-left: 15px;z-index:2'>
{% endblock %} 

        {% block usersORchats%}
        <link type="text/css" rel="stylesheet" href="{% static 'css/message.css' %}">
            <h1 class='titleDesc'>{{ chat.name }}</h1>

          <h1 class='titleDesc'>Users:</h1>

          {% for member in members %}
            <div class="dropdown">
              <h4 class="userName">{{member.username}}</h4>
            </div>   
          {% endfor %}

        {% endblock %}
    </div>
</div>

<div class="col-12 col-sm-12 col-md-9 px-0">
    <div class="card">
        <div id="board" class="nightmode_changed_color section">

            {% block mess%}
                {% for message in messages %}
                    {% if message.author == user %}

                        <div class="card-panel right" id='featureItemYou'>
                            <div class="itemPosition title">You</div>
                            {{ message.message }}
                        </div>

                    {% else %}
                        <div class="card-panel left blue lighten-5" id='featureItemSome'>
                            <div class="itemPosition title">{{ message.author }}</div>
                            {{ message.message }}
                        </div>
                    {% endif %}
                {% endfor %}

                <script>
                    function scrollDown() {
                        let elem = document.getElementById('board');
                        document.getElementById('board').scrollTop = elem.scrollHeight;
                    }
                    scrollDown();

                    let id = "{{ chat.id|safe }}";
                    let user_name = "{{ user.username|safe }}";
                    let host = "{{ host|safe }}";
                </script>
                <script type="text/javascript" src="{% static 'js/sendmessage.js' %}"></script>
                <script type="text/javascript" src="{% static 'js/copied.js' %}"></script>
                {% endblock %}

            
                        
            <form id="chat-box" class="form-group" method="post">
                {% csrf_token %}
                {% block input%}
                
                <div class="write_message">
                    
                    <div class="input_message__position">
                        <div class="input-field">
                            <input autocomplete="off" id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>

                    <div id='tooltip' class="icon_message__position">
                        <button id='click_button' class="btn btn-floating blue lighten-2 waves-effect waves-light" onmouseout="outFunc()">
                            <i class="fa fa-user-plus" aria-hidden="true"></i>
                        </button>
                        <span class="tooltiptext" id="myTooltip">Generate Invite Link</span>
                    </div>

                    <div class="icon_message__position">
                        <button id='sendmessage' class="btn btn-floating blue lighten-2 waves-effect waves-light">
                            <i class="material-icons">send</i></button>
                    </div>
                </div>
                {% endblock %}
            </form>
            
        </div>
    </div>
</div>

Full_project/templates/chat/register.html
{% extends 'chat/index.html' %}

{% block form %}
    <form id="register-form" class="login100-form validate-form form-group" method="post">
        {% csrf_token %}

        <span class="login100-form-title p-b-34">
            Account Register
        </span>


        <div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20 " data-validate="Type user name"
            style="width: 100%;">
            <label for="id_username" data-error="Username already taken">Username</label>
            {{ form.username }}
            <span class="focus-input100"></span>
        </div>


        <div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20 " data-validate="Type user name"
            style="width: 100%;">
            <label for="email" data-error="None">Email</label>
            {{form.email}}
            <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20 " data-validate="Type user name"
            style="width: 100%;">
            <label for="id_password">Password</label>
            {{form.password1}}
            <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20 " data-validate="Type user name"
            style="width: 100%;">
            <label for="id_password2">Repeat Password</label>
            {{form.password2}}
            <span class="focus-input100"></span>
        </div>

        <div class="container-login100-form-btn">
            <button name="login" class="login100-form-btn">
                Register
            </button>
        </div>

        <div class="w-full text-center p-t-27 p-b-89">
            <!--<span class="txt1">
                Forgot
            </span>

            <a href="#" class="txt2">
                User name / password?
            </a>-->
        </div>

        <div class="w-full text-center">
            <a href="{% url 'index' %}" class="txt3">
                Sign IN
            </a>
        </div>
        
    </form>


    {% load static %}
    <img class="login100-more" src="{% static 'img/login.jpg' %}" alt="Image">
{% endblock %}